server:
  port: 2003
  servlet:
    session:
      #Session超时时间设置为5小时，单位是秒，默认是30分钟
      timeout: 18000
spring:
  thymeleaf:
    cache: false
  datasource:
    url: jdbc:mysql://localhost:3306/hzy2003?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=CONVERT_TO_NULL
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver

  freemarker:
    # 设置模板后缀名
    suffix: .ftl
    # 设置文档类型
    content-type: text/html
    # 设置页面编码格式
    charset: UTF-8
    # 设置页面缓存
    cache: true
    settings:
      number_format: 0.##
  web:
    resources:
      static-locations: classpath:static/,file:static/

mybatis-plus:
  type-aliases-package: com.hzy2003.entity
  configuration:
    call-setters-on-nulls: false
    #开启驼峰
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full

  mapper-locations: classpath*:mapper/**/*Mapper.xml
  global-config:
    banner: true
    db-config:
      logic-not-delete-value: 1
      logic-delete-value: 0


logging:
  level:
    root: error #日志配置DEBUG,INFO,WARN,ERROR